std = "lua51"
max_line_length = 160
allow_defined_top = true

ignore = {
    "631", -- line is too long
    "212", -- unused argument
    "211/ADDON_NAME", -- unused local ADDON_NAME
    "211/WARN", -- unused local WARN
    "431", -- shadowing upvalue
    "131", -- unused global variable (e.g. SLASH commands)
}

read_globals = {
    -- Lua 5.1 / OS
    "bit",
    "date",

    -- String / Table utils
    "strtrim",
    "strsplit",
    "strjoin",
    "tinsert",
    "tremove",
    "tContains",
    "wipe",
    "CopyTable",

    -- Blizzard FrameXML & UI
    "UIParent",
    "GlueParent",
    "CreateFrame",
    "hooksecurefunc",
    "InCombatLockdown",
    "PlaySound",
    "SOUNDKIT",
    "Settings",
    "CreateColor",
    "NORMAL_FONT_COLOR",
    "GRAY_FONT_COLOR",
    "RED_FONT_COLOR",
    "GREEN_FONT_COLOR",
    "YELLOW_FONT_COLOR",
    "OKAY",
    "CANCEL",
    "ACCEPT",
    "CLOSE",
    "CUSTOM",
    "GameTooltip",
    "DEFAULT_CHAT_FRAME",
    "Enum",
    "Mixin",
    "CreateAnchor",
    "GetTime",
    "GetBuildInfo",
    "GetAddOnMetadata",
    "GetRealmName",
    "UISpecialFrames",
    "BACKDROP_DIALOG_32_32",
    "ScrollUtil",
    "LowHealthFrame",
    "GetMirrorTimerProgress",
    "GetMirrorTimerInfo",
    "TabSystemMixin",
    "TabSystemOwnerMixin",
    "PanelTemplates_SetTab",
    "StackSplitFrame",

    -- Blizzard Modern C_* namespaces
    "C_AddOns",
    "C_Spell",
    "C_Container",
    "C_Item",
    "C_Timer",
    "C_PlayerInfo",
    "C_UnitAuras",
    "C_Curve",
    "C_GamePad",
    "C_CVar",
    "C_TradeSkillUI",
    "C_EncounterEvents",
    "C_Weather",
    "C_Cursor",
    "C_EventUtils",
    "C_LossOfControl",
    "C_CooldownViewer",
    "C_SwingTimer",
    "EventRegistry",

    -- Classic & Unit APIs
    "UnitHealth",
    "UnitHealthMax",
    "UnitPower",
    "UnitPowerMax",
    "UnitGUID",
    "UnitName",
    "UnitClass",
    "UnitRace",
    "UnitAura",
    "UnitBuff",
    "UnitDebuff",
    "UnitIsDeadOrGhost",
    "UnitCanAttack",
    "UnitExists",
    "UnitAffectingCombat",
    "UnitCastingInfo",
    "UnitChannelInfo",
    "UnitOnTaxi",
    "UnitIsUnit",
    "UnitIsAFK",
    "UnitIsDND",
    "UnitThreatSituation",
    "UnitAttackSpeed",
    "GetMeleeHaste",
    "CheckInteractDistance",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetMaxBattlefieldID",
    "GetBattlefieldStatus",
    "IsStealthed",
    "IsEncounterInProgress",
    "IsMounted",
    "IsFlying",
    "IsSwimming",
    "IsFalling",
    "IsSubmerged",
    "IsSpellKnown",
    "GetUnitSpeed",
    "GetInventoryItemID",
    "GetShapeshiftFormID",
    "GetShapeshiftForm",
    "GetProfessions",
    "GetProfessionInfo",
    "GetMoney",
    "issecretvalue",
    "LE_GAME_ERR_ATTACK_DEAD",

    -- Controller & Navigation / ConsolePort integration
    "SmartNavigation",
    "SmartNavigation_SetCustomCursorAnchorPointForFrame",
    "SmartNavigation_AddIgnoreInputNavigationOverride",
    "SmartNavigation_MarkFrameIgnored",
    "SmartNavigation_MarkFrameFocusable",
    "SmartNavigation_ClearIgnoreStatus",
    "SmartNavigation_MarkFrameSubSection",
    "SmartNavigation_AddJumpNavigationOverride",
    "SMART_NAV_INPUT_DIRECTION",
    "MinimalSliderWithSteppersMixin",
    "InputUtil",
    "GamepadSharedUtility",
    "GamepadMode",
    "GamepadRadial",
    "GAMEPAD_DPAD_LEFT",
    "GAMEPAD_DPAD_RIGHT",
    "GAMEPAD_FACE_TOP",
    "GAMEPAD_FACE_BOTTOM",
}

globals = {
    "Pulse",
    "PulseDB",
    "PulseCharDB",
    "PulseChecklistDB",
    "PulseDebugDB",
    "PulseDebugUI",
    "SlashCmdList",
    "SLASH_PULSE1",
    "SLASH_PULSEUI1",
    "SLASH_PULSEUI2",
    "SLASH_PULSECHECKLIST1",
    "SLASH_PULSECHECKLIST2",
    "SLASH_PULSEDEBUG1",
    "SLASH_PULSEDEBUG2",
    "SLASH_PULSEDEBUGUI1",
}

exclude_files = {
    "PulseChecklist/tests/**",
    "_reference/**",
}
